//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.8.3928.0。
// 
namespace OfficeAssitant {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchema1.xsd", IsNullable=false)]
    public partial class Kp {
        
        private string versionField;
        
        private KpFpxx fpxxField;
        
        public Kp() {
            this.versionField = "2.0";
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public KpFpxx Fpxx {
            get {
                return this.fpxxField;
            }
            set {
                this.fpxxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class KpFpxx {
        
        private int zslField;
        
        private KpFpxxFpsj fpsjField;
        
        /// <remarks/>
        public int Zsl {
            get {
                return this.zslField;
            }
            set {
                this.zslField = value;
            }
        }
        
        /// <remarks/>
        public KpFpxxFpsj Fpsj {
            get {
                return this.fpsjField;
            }
            set {
                this.fpsjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class KpFpxxFpsj {
        
        private KpFpxxFpsjFP[] fpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fp")]
        public KpFpxxFpsjFP[] Fp {
            get {
                return this.fpField;
            }
            set {
                this.fpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class KpFpxxFpsjFP {
        
        private string djhField;
        
        private string gfmcField;
        
        private string gfshField;
        
        private string gfyhzhField;
        
        private string gfdzdhField;
        
        private string bzField;
        
        private string fhrField;
        
        private string skrField;
        
        private string spbmbbhField;
        
        private string hsbzField;
        
        private KpFpxxFpsjFPSpxx spxxField;
        
        public KpFpxxFpsjFP() {
            this.djhField = "1";
            this.gfmcField = "";
            this.gfshField = "";
            this.gfyhzhField = "";
            this.gfdzdhField = "";
            this.bzField = "";
            this.fhrField = "";
            this.skrField = "";
            this.spbmbbhField = "40.0";
            this.hsbzField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string Djh {
            get {
                return this.djhField;
            }
            set {
                this.djhField = value;
            }
        }
        
        /// <remarks/>
        public string Gfmc {
            get {
                return this.gfmcField;
            }
            set {
                this.gfmcField = value;
            }
        }
        
        /// <remarks/>
        public string Gfsh {
            get {
                return this.gfshField;
            }
            set {
                this.gfshField = value;
            }
        }
        
        /// <remarks/>
        public string Gfyhzh {
            get {
                return this.gfyhzhField;
            }
            set {
                this.gfyhzhField = value;
            }
        }
        
        /// <remarks/>
        public string Gfdzdh {
            get {
                return this.gfdzdhField;
            }
            set {
                this.gfdzdhField = value;
            }
        }
        
        /// <remarks/>
        public string Bz {
            get {
                return this.bzField;
            }
            set {
                this.bzField = value;
            }
        }
        
        /// <remarks/>
        public string Fhr {
            get {
                return this.fhrField;
            }
            set {
                this.fhrField = value;
            }
        }
        
        /// <remarks/>
        public string Skr {
            get {
                return this.skrField;
            }
            set {
                this.skrField = value;
            }
        }
        
        /// <remarks/>
        public string Spbmbbh {
            get {
                return this.spbmbbhField;
            }
            set {
                this.spbmbbhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string Hsbz {
            get {
                return this.hsbzField;
            }
            set {
                this.hsbzField = value;
            }
        }
        
        /// <remarks/>
        public KpFpxxFpsjFPSpxx Spxx {
            get {
                return this.spxxField;
            }
            set {
                this.spxxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class KpFpxxFpsjFPSpxx {
        
        private KpFpxxFpsjFPSpxxSph[] sphField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sph")]
        public KpFpxxFpsjFPSpxxSph[] Sph {
            get {
                return this.sphField;
            }
            set {
                this.sphField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class KpFpxxFpsjFPSpxxSph {
        
        private int xhField;
        
        private string spmcField;
        
        private string ggxhField;
        
        private string jldwField;
        
        private string spbmField;
        
        private string qyspbmField;
        
        private string syyhzcbzField;
        
        private string lslbzField;
        
        private string yhzcsmField;
        
        private double djField;
        
        private double slField;
        
        private double jeField;
        
        private double slvField;
        
        private double seField;
        
        private double kceField;
        
        public KpFpxxFpsjFPSpxxSph() {
            this.xhField = 1;
            this.ggxhField = "";
            this.jldwField = "";
            this.qyspbmField = "";
            this.syyhzcbzField = "0";
            this.lslbzField = "";
            this.yhzcsmField = "";
            this.kceField = 0D;
        }
        
        /// <remarks/>
        public int Xh {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
            }
        }
        
        /// <remarks/>
        public string Spmc {
            get {
                return this.spmcField;
            }
            set {
                this.spmcField = value;
            }
        }
        
        /// <remarks/>
        public string Ggxh {
            get {
                return this.ggxhField;
            }
            set {
                this.ggxhField = value;
            }
        }
        
        /// <remarks/>
        public string Jldw {
            get {
                return this.jldwField;
            }
            set {
                this.jldwField = value;
            }
        }
        
        /// <remarks/>
        public string Spbm {
            get {
                return this.spbmField;
            }
            set {
                this.spbmField = value;
            }
        }
        
        /// <remarks/>
        public string Qyspbm {
            get {
                return this.qyspbmField;
            }
            set {
                this.qyspbmField = value;
            }
        }
        
        /// <remarks/>
        public string Syyhzcbz {
            get {
                return this.syyhzcbzField;
            }
            set {
                this.syyhzcbzField = value;
            }
        }
        
        /// <remarks/>
        public string Lslbz {
            get {
                return this.lslbzField;
            }
            set {
                this.lslbzField = value;
            }
        }
        
        /// <remarks/>
        public string Yhzcsm {
            get {
                return this.yhzcsmField;
            }
            set {
                this.yhzcsmField = value;
            }
        }
        
        /// <remarks/>
        public double Dj {
            get {
                return this.djField;
            }
            set {
                this.djField = value;
            }
        }
        
        /// <remarks/>
        public double Sl {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        public double Je {
            get {
                return this.jeField;
            }
            set {
                this.jeField = value;
            }
        }
        
        /// <remarks/>
        public double Slv {
            get {
                return this.slvField;
            }
            set {
                this.slvField = value;
            }
        }
        
        /// <remarks/>
        public double Se {
            get {
                return this.seField;
            }
            set {
                this.seField = value;
            }
        }
        
        /// <remarks/>
        public double Kce {
            get {
                return this.kceField;
            }
            set {
                this.kceField = value;
            }
        }
    }
}
